In [2]:
from sklearn.datasets import load_iris
li= load_iris()

In [11]:
import pandas as pd
df= pd.DataFrame(li.data,columns=li.feature_names)
df['flower']= li.target
df['flower']= df['flower'].apply(lambda x: li.target_names[x])
df[47:55]


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

        flower  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor  
52  versicolor  
53  versicolor  
54  versicolor

In [48]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(li.data,li.target, test_size=0.2)

In [61]:
from sklearn.svm import SVC
meth_1=SVC(kernel='rbf',C=10,gamma='auto')
meth_2=SVC(kernel='linear',C=10,gamma='auto')
meth_3=SVC(kernel='rbf',C=20,gamma='auto')

In [62]:
meth_1.fit(x_train,y_train)

SVC(C=10, gamma='auto')

In [63]:
meth_1.score(x_train,y_train)

0.9916666666666667

In [64]:
from sklearn.model_selection import cross_val_score


In [65]:
cross_val_score(meth_1,li.data,li.target,cv=2)

array([0.96      , 0.98666667])

In [66]:
cross_val_score(meth_2,li.data,li.target,cv=2)

array([0.97333333, 0.98666667])

In [67]:
cross_val_score(meth_3,li.data,li.target,cv=2)

array([0.96, 0.92])

In [68]:
#For Loop.................

In [75]:
import numpy as np
kernels=['rbf', 'linear']
C= [1,10,20]
avg_scores= {}
for kval in kernels:
    for cval in C:
        cv_score= cross_val_score(SVC(kernel=kval, C=cval,gamma='auto'),li.data,li.target,cv=2)
        avg_scores[kval +'__'+ str(cval)]= np.average(cv_score)
        
avg_scores

{'rbf__1': 0.9466666666666667,
 'rbf__10': 0.9733333333333334,
 'rbf__20': 0.94,
 'linear__1': 0.9666666666666667,
 'linear__10': 0.98,
 'linear__20': 0.9666666666666667}

In [79]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(SVC(gamma='auto'),{
    'C': [1,10,20],
    'kernel':['rbf','linear']
},cv=5, return_train_score=False)
clf.fit(li.data,li.target)
clf.cv_results_

{'mean_fit_time': array([0.00162563, 0.00134735, 0.00100708, 0.00063906, 0.00084715,
        0.00059905]),
 'std_fit_time': array([6.80192296e-04, 4.36409052e-04, 1.33403664e-05, 4.49244951e-04,
        5.12887816e-04, 4.89124849e-04]),
 'mean_score_time': array([7.03716278e-04, 9.00173187e-04, 8.84532928e-05, 1.77860260e-04,
        2.95257568e-04, 4.07457352e-04]),
 'std_score_time': array([0.00055491, 0.00066031, 0.00017691, 0.00035572, 0.00059052,
        0.00049921]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'ker

In [84]:
df= pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001626      0.000680         0.000704        0.000555       1   
1       0.001347      0.000436         0.000900        0.000660       1   
2       0.001007      0.000013         0.000088        0.000177      10   
3       0.000639      0.000449         0.000178        0.000356      10   
4       0.000847      0.000513         0.000295        0.000591      20   
5       0.000599      0.000489         0.000407        0.000499      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [85]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [86]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [118]:
from sklearn.model_selection import RandomizedSearchCV

rs = RandomizedSearchCV(SVC(gamma='auto'),{
    'C': [1,10,20],
    'kernel':['rbf','linear']
},cv=5, return_train_score=False, n_iter=4)
rs.fit(li.data,li.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      10       linear         0.973333
1      10          rbf         0.980000
2      20       linear         0.966667
3       1       linear         0.980000