In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(iris.data, iris.target,test_size=0.2)

In [3]:
len(x_train)

120

In [4]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [5]:
lr= LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [6]:
sv= SVC()
sv.fit(x_train,y_train)
sv.score(x_test,y_test)

0.9666666666666667

In [7]:
rfc =RandomForestClassifier()
rfc.fit(x_train,y_train)
rfc.score(x_test,y_test)

0.9666666666666667

In [8]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [11]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print (train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [12]:
def check_score(model, x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [13]:
from sklearn.model_selection import StratifiedKFold
folds= StratifiedKFold(n_splits=5)

In [14]:
score_lr=[]
score_svm=[]
score_rf=[]

for train_index, test_index in kf.split(iris.data):
    x_train, x_test, y_train, y_test = iris.data[train_index],iris.data[test_index],iris.target[train_index],iris.target[train_index]
    
    score_lr.append(check_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    score_svm.append(check_score(SVC(),x_train,x_test,y_train,y_test))
    score_rf.append(check_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

ValueError: Found input variables with inconsistent numbers of samples: [100, 50]

In [15]:
from sklearn.model_selection import cross_val_score

In [17]:
cross_val_score(LogisticRegression(),iris.data, iris.target)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [18]:
cross_val_score(SVC(),iris.data, iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [21]:
cross_val_score(RandomForestClassifier(n_estimators=100),iris.data, iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])